name: Build
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18.1.0'
      - run: yarn install
      - run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          VITE_CONTRACT_ID: ${{secrets.VITE_CONTRACT_ID}}
          VITE_GAME_API_URL: ${{secrets.VITE_GAME_API_URL}}
          VITE_API_URL: ${{secrets.VITE_API_URL}}
          VITE_PARAS_API_URL: ${{secrets.VITE_PARAS_API_URL}}
